### PR TITLE
fix automation scripts to use python3

### PR DESCRIPTION
**Pull request by wbgilmartin**
change the automation provisioning scripts to use python3 rather than the default (python2) version.

### CODE REVIEW

**Review by zaliu — COMMENTED** [review]
@wbgilmartin did you confirm that the massage script and the convert script work correctly with python3?  I know  the merge script requires python3, but I'm not sure about the remaining 5 instances.  Thanks.

**Comment by wbgilmartin** [comment]
> @wbgilmartin did you confirm that the massage script and the convert script work correctly with python3? I know the merge script requires python3, but I'm not sure about the remaining 5 instances. Thanks.

I did verify everything except the arcturus section in the provisioning verification section. The rocmdevtools git dose not seem to exist. Do you know anything about this?

**Comment by zaliu** [comment]
> The rocmdevtools git dose not seem to exist. Do you know anything about this?

It's a private repo.  Once your status gets corrected from "external collaborator" to AMD people, you should be able to see that repo.

**Review by zaliu — APPROVED** [review]

**Comment by zaliu** [comment]
@wbgilmartin are you able to merge this PR?  Let me know.  Thanks.

**Pull request merged**
