### PR TITLE
Add Denorm testing for Assembly Kernels

### PR DESCRIPTION
**Pull request by yoichiyoshida**
- Adding denorm testing for assembly kernels
- Adding header to force assembly kernels to keep denorms and not flush to 0

### CODE REVIEW

**Comment by cgmb** [comment]
> Adding header to force assembly kernels to keep denorms and not flush to 0

Does this mean that assembly kernels for rocBLAS are currently using FTZ by default?

**Comment by yoichiyoshida** [comment]
> > Adding header to force assembly kernels to keep denorms and not flush to 0
> 
> Does this mean that assembly kernels for rocBLAS are currently using FTZ by default?

Before we did not explicitly set the flags, so depended on the compiler/assembler defaults for FTZ behaviour. In the current version, the assembler defaults are to not FTZ for 16/64 but FTZ for 32, for instructions that follow the flags (mostly FMA, but SGEMM MFMA as well). The compiler (for source kernels) was setting not FTZ for 32, differing with the assembler. With this new change we will force the setting to never flush for all assembler cases.

**Review by zaliu — APPROVED** [review]
All pipelines passed at least once.  Please squash-merge after @AlexBrownAMD reviewed and OKed this PR.  Thanks!

**Comment by zaliu** [comment]
@bragadeesh Please decide if we want to let this PR in.  I recommend it.  Thanks.

**Review by bragadeesh — APPROVED** [review]

**Review by AlexBrownAMD — APPROVED** [review]
LG

**Pull request merged**
