### PR TITLE
merge staging db22912d into master on GO from CQE

### PR DESCRIPTION
**Pull request by zaliu**

### CODE REVIEW

**Comment by zaliu** [comment]
@benjaminulmer @yoichiyoshida FYI, this PR corresponds to rocBLAS-internal [#1103](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/1103).  We always do incremental merging from staging to master in sync with rocBLAS (*after* the current ROCm release branched) soon after CQE/QA gave us the thumbs-up on their staging build, functional and performance tests.  The Tensile commit hash stored in tensile_tag.txt in [#1103](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/1103) is used to perform the incremental merging for Tensile.

**Review by TorreZuk — APPROVED** [review]
Only verified the tensile tag in rocblas matches current master last commit.  So not sure what CQE verified so @amcamd will you need to edit the rocblas master tensile tag after this goes into master or was it only verified back to the Jan19 commit?  More question on rocblas than this merge.

**Comment by TorreZuk** [comment]
Okay confirm now the rocBLAS commit [5ca09bc] mentioned as validation report has tensile tag commit db22912 (had looked at earlier wrong validation report of master when the tensile PR review started, and the correct one for rocblas PR),  We only expect the tensile_tag commit is included and may not be tip as that isn't required but it is the tip.    So both PRs looks good to me.

**Comment by benjaminulmer** [comment]
Thanks for the info Alex. I'm slowly getting a grip on all these processes.

**Review by amcamd — APPROVED** [review]

**Pull request merged**
