### PR TITLE
Updated CMakeLists.txt to stop errors from raw manipulation of CMAKE_CXX_FLAGS

### PR DESCRIPTION
**Pull request by lringham**
Updated CMakeLists.txt to a more modern style to stop errors from raw manipulation of CMAKE_CXX_FLAGS.

### CODE REVIEW

**Review by AlexBrownAMD — APPROVED** [review]
lgtm

**Review by sdquiring — APPROVED** [review]

**Review by zaliu — APPROVED** [review]
Full rocBLAS build succeeded without those pesky CMAKE warnings.  The remaining 2 warnings can be handled by @imcarsonliao's team, I mean the 2 warnings with "error 5":
`Generating kernel source resulted in error 5
`

**Comment by zaliu** [comment]
Please squash-merge.  Thanks.

**Review by TorreZuk — APPROVED** [review]
LGTM but double check tensile_client target is covered as much as required.  I know that one caused trouble for me and OpenMP.   When you replace a global you need to ensure all the targets are now manually covered.

**Review by JeremyAdamHart — APPROVED** [review]

**Pull request merged**
