### PR TITLE
Merge hotfixes from rocm-rel-5.3 into develop

### PR DESCRIPTION
**Pull request by benjaminulmer**
Captures an actual hotfix and the changelog updates for 5.3

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
This needs a quick review and merge today we want to try and pick up in rocblas feature complete today?    I know improvements are planned (and suggested) but best to start off with LKG solution for 5.3 for 5.4

**Comment by benjaminulmer** [comment]
Yes this should get merged today and then we can make a manual tag update on the rocBLAS side

**Review by AlexBrownAMD — APPROVED** [review]
lgtm

**Comment by benjaminulmer** [comment]
CI issues are showing up in develop too, so unlikely it's related to these changes.

**Pull request merged**
