### PR TITLE
Initial commit for aquavanjaram support

### PR DESCRIPTION
**Pull request by yoichiyoshida**
Initial commit for aquavanjaram support
 - adds support for gfx940/gfx941/gfx942
 - adds fp8/bf8 datatype support
 - adds xf32 datatype support
 - adds stochastic rounding support for various datatypes

Co-authored-by: Koji Nakajima <75698246+nakajee@users.noreply.github.com>
Co-authored-by: Majed Sujon <majed.sujon@amd.com>
Co-authored-by: Alex Brown <alex.brown@amd.com>
Co-authored-by: Vin Huang <vin.huang@amd.com>
Co-authored-by: Babak Poursartip <babak.poursartip@amd.com>

### CODE REVIEW

**Review by babakpst — APPROVED** [review]

**Comment by nakajee** [comment]
Please fix static analysis fail

**Review by nakajee — APPROVED** [review]

**Comment by nakajee** [comment]
dgemm_large_offset.yaml failed with the following error.
 RuntimeError: No valid solutions found

Would you please check why it fails?

**Comment by nakajee** [comment]
> dgemm_large_offset.yaml failed with the following error. RuntimeError: No valid solutions found
> 
> Would you please check why it fails?

I just got an email about the fail.
Not sure if it is based on the latest code.

**Comment by AlexBrownAMD** [comment]
> dgemm_large_offset.yaml failed with the following error. RuntimeError: No valid solutions found
Large offset test was designed for a particular case on 90a. Updated it to add a case ("FMA") so large offset can be tested on 940 also.

**Comment by nakajee** [comment]
Did prechecking build fail?

**Comment by AlexBrownAMD** [comment]
> Did prechecking build fail?

Looks like clang-format re-organized some includes and that broke a dependency in one of the files. Should be fixed in latest commit.

**Comment by nakajee** [comment]
Some gfx90a extended cases failed. Would you check why they failed?

**Review by AlexBrownAMD — APPROVED** [review]

**Pull request merged**
