### PR TITLE
Koji's custom kernel DGEMM_Aldebaran_PKFixedAtomic512Latest

### PR DESCRIPTION
**Pull request by zaliu**

### CODE REVIEW

**Comment by nakajee** [comment]
Have you verified this kernel?
Did all tests pass?

**Comment by zaliu** [comment]
For the 3 sizes using this custom kernel, they validated in Tensile.  rocblas-test passed fully (quick, pre_checkin and nightly).

**Review by yoichiyoshida — COMMENTED** [review]
Is the word latest needed for part of the kernel name? Seems to not add anything?

**Comment by zaliu** [comment]
I respect the author's choice of kernel name, hence keeping the "Latest" suffix.  We don't care about the color of the bike shed, do we?  If you insist, I'll rename it.

**Review by yoichiyoshida — APPROVED** [review]

**Pull request merged**
