### PR TITLE
Reduced max ram usage and optimized runtime of TensileCreateLibraries

### PR DESCRIPTION
**Pull request by lringham**
- Refactored some code into its own method to reduce memory used
- Enabled control over the maxtasksperchild value during multiprocessing to avoid reusing processes to save on memory usage
- Optimized the runtime of code that runs at the initial stage of TensileCreateLibraries

Overall memory usage is down by ~15GB and runtime is about 30% faster when running for all architectures

Tests passed:
- linting
- kernel unit tests
- client tests

### CODE REVIEW

**Comment by TorreZuk** [comment]
Looks good to me, but that last commit you probably could have just put in a new PR.  PRs are cheap :-)  That way you can squash and merge to clean up a dirty PR but you still have separate functionality to back out  easily in a separate commit/PR.

**Comment by lringham** [comment]
> Looks good to me, but that last commit you probably could have just put in a new PR. PRs are cheap :-) That way you can squash and merge to clean up a dirty PR but you still have separate functionality to back out easily in a separate commit/PR.

Okay, I've taken out the last commit and will put it into a new PR. Thanks!

**Review by sdquiring — APPROVED** [review]
LGTM

**Review by JeremyAdamHart — APPROVED** [review]
lgtm

**Pull request merged**
