### PR TITLE
Switch CI to use python 3.6 environment for tests run on tox

### PR DESCRIPTION
**Pull request by AlexBrownAMD**

### CODE REVIEW

**Comment by zaliu** [comment]
Can we please do an extended run also?  Thanks!

**Comment by AlexBrownAMD** [comment]
Current test failures are because rocm-docker is using 3.5.1 hipclang instead of an hcc build

**Comment by amdkila** [comment]
> Current test failures are because rocm-docker is using 3.5.1 hipclang instead of an hcc build

This problem will go away soon...there's a CI change that needs to be made first. I've opened a PR with the tag change.

**Comment by amdkila** [comment]
I started a precheckin hcc build, plus an extended one. There's already an extended hip-clang build in progress

**Comment by saadrahim** [comment]
Extended tests still failing. So close.

**Comment by rosenrodt** [comment]
> Extended tests still failing. So close.

Could be a long standing hcc bug as described in SWDEV-197382

**Comment by zaliu** [comment]
> > Extended tests still failing. So close.
> 
> Could be a long standing hcc bug as described in SWDEV-197382

My offline extended run with hipclang also failed.

**Comment by AlexBrownAMD** [comment]
> > > Extended tests still failing. So close.
> > 
> > 
> > Could be a long standing hcc bug as described in SWDEV-197382
> 
> My offline extended run with hipclang also failed.

I think the double_complex failures are an unresolved hcc bug, we may need a mark to skip these tests on hcc for now. Which tests did you see failing on hipclang?

**Comment by saadrahim** [comment]
I think we should merge this change is as a partial fix. precheckin tests will pass with this. After that we should get the extended tests looked at. They are currently timing out at 7 hours at 42%. That is implying a 17 hour test run.

**Comment by zaliu** [comment]
> > > > Extended tests still failing. So close.
> > > 
> > > 
> > > Could be a long standing hcc bug as described in SWDEV-197382
> > 
> > 
> > My offline extended run with hipclang also failed.
> 
> I think the double_complex failures are an unresolved hcc bug, we may need a mark to skip these tests on hcc for now. Which tests did you see failing on hipclang?

Note that I'm running extended without this PR.
On arcturus (-n 1) it's stuck at:
Tensile/Tests/extended/convolution_config/test_forward_nchw.py::test_nchw_filter7x1[Run_Contraction-asm3_splitu-inception]
top shows:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
50582 root      20   0 9664404 590976  70940 R 200.3  0.2   1495:21 tensile_cl+
It doesn't seem to want to finish.

On gfx906 (-n 4), it's still running, but closer to the finish line (currently at 88%):
[gw2] [ 47%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter2x2[Run_Contraction-asm3_pbd-default_sizes]
[gw2] [ 48%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter2x2[Run_Contraction-asm3_pbd-resnet]
[gw2] [ 49%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter2x2[Run_Contraction-asm3_pbd-inception]
[gw2] [ 50%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter2x2[Run_Contraction-asm3_splitu-default_sizes]
[gw2] [ 51%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter2x2[Run_Contraction-asm3_splitu-resnet]
[gw2] [ 52%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter2x2[Run_Contraction-asm3_splitu-inception]
[gw2] [ 54%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter2x1_dilation[Run_Contraction-asm3_pbd]
[gw2] [ 59%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter2x1_dilation[Run_Contraction-asm3_splitu]
[gw1] [ 60%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_dilation_filter4x4_pad[Run_Contraction-asm3_splitu]
[gw1] [ 63%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_stride_filter[Run_Contraction-asm3_pbd]
[gw2] [ 63%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter1x2[Run_Contraction-asm3_pbd]
[gw1] [ 63%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_stride_filter[Run_Contraction-asm3_splitu]
[gw2] [ 67%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter1x2[Run_Contraction-asm3_splitu]
[gw3] [ 68%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter7x1[Run_Contraction-asm3_pbd-default_sizes]
[gw3] [ 69%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter7x1[Run_Contraction-asm3_pbd-resnet]
[gw3] [ 70%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter7x1[Run_Contraction-asm3_pbd-inception]
[gw2] [ 70%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter1x2_dilation[Run_Contraction-asm3_pbd]
[gw2] [ 71%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter1x2_dilation[Run_Contraction-asm3_splitu]
[gw3] [ 71%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter7x1[Run_Contraction-asm3_splitu-default_sizes]
[gw3] [ 74%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter7x1[Run_Contraction-asm3_splitu-resnet]
[gw3] [ 75%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_filter7x1[Run_Contraction-asm3_splitu-inception]
[gw0] [ 76%] FAILED Tensile/Tests/yaml_only/test_config.py::test_config[Tensile/Tests/extended/zeropad/test_zp_simple_2sum_zp_both.yaml]
[gw2] [ 77%] FAILED Tensile/Tests/extended/convolution_config/test_forward_pad.py::test_nchw_dilation_filter4x4_pad[Run_Contraction-asm3_pbd]

**Pull request merged**
