### PR TITLE
fix  warning: anonymous non-C compat type

### PR DESCRIPTION
**Pull request by TorreZuk**
* fixes many warnings when compiling kernels in rocBLAS

### CODE REVIEW

**Comment by TorreZuk** [comment]
Linkage symbol probably not required anyway so just made local instances of the union.  Typedefs probably would not be declared inside helper function but in separate file with some form of naming standardization.

**Comment by amdkila** [comment]
This looks fine to me, but I will let Scott review this as the code you've edited is not one that I've worked on.

**Comment by leekillough** [comment]
This is why, for example:

https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/blob/acdac7474b1148ef5672042b2158d2b85a650c84/library/include/rocblas-types.h#L62

has `struct rocblas_half` and `typedef ... rocblas_half` both declared.

**Comment by leekillough** [comment]
The warning is that a `struct` or `union` without a tag is anonymous, and thus not C-compatible. Simply supply a tag the same name as the type, and it will be happy.

**Pull request merged**
