### PR TITLE
Hotfix: Fix override when lazy loading (#1756)

### PR DESCRIPTION
**Pull request by nielenventer**
* fix override for unloaded solutions

* fix index

* better debug message for override

* clang-format

### CODE REVIEW

**Comment by nielenventer** [comment]
Linked ticket: https://ontrack-internal.amd.com/browse/SWDEV-418497

**Comment by nielenventer** [comment]
This is the cherry pick of this change for the release branch: https://github.com/ROCmSoftwarePlatform/Tensile/pull/1756

**Comment by nielenventer** [comment]
prev failure was memory issue on CI machine, current failure is:
[  FAILED  ] 1 test, listed below:
[  FAILED  ] OclSolutionAdapterTest.HardwareTest

which seems unrelated

**Comment by babakpst** [comment]
I have not seen this error before. Can you please rerun the tests again?

**Comment by nielenventer** [comment]
Or alternatively, we could merge this, since all other tests passed? The same commit was also passing on the tensile dev branch, so I think the change itself is safe.

**Comment by nielenventer** [comment]
Closed, will be merged in 5.7.1 instead of hotfixed

**Pull request closed without merging**
