### PR TITLE
    Revert "Add dual mac insttruction for gfx11."

### PR DESCRIPTION
**Pull request by cmingch**
This reverts commit 78a8c51496a7ac5b58d6976009e08bd42a14258f.

### CODE REVIEW

**Review by imcarsonliao — APPROVED** [review]

**Review by yoichiyoshida — APPROVED** [review]

**Comment by nakajee** [comment]
The previous commit is not fully reverted.
https://github.com/ROCmSoftwarePlatform/Tensile/commit/e98916f9ca3f76a96b8cd81117b24f7488b720a5#diff-fb6a686182f16eb54af3c628f38593f347f68aba31de903983023c560288d7a1

- popAllInstructions related code should be deleted
- 4 test cases in wave32 folder are not removed
- also, need to remove wave32 from pytest.ini

**Comment by cmingch** [comment]
> The previous commit is not fully reverted. [e98916f#diff-fb6a686182f16eb54af3c628f38593f347f68aba31de903983023c560288d7a1](https://github.com/ROCmSoftwarePlatform/Tensile/commit/e98916f9ca3f76a96b8cd81117b24f7488b720a5#diff-fb6a686182f16eb54af3c628f38593f347f68aba31de903983023c560288d7a1)
> 
> * popAllInstructions related code should be deleted
> * 4 test cases in wave32 folder are not removed
> * also, need to remove wave32 from pytest.ini

done

**Comment by nakajee** [comment]
> done

Thanks for your update. Please make sure all CI tests pass.

**Comment by eidenyoshida** [comment]
Looks like it passed the 5.5 precheckin but failed the 5.4 extended

**Pull request merged**
