### PR TITLE
Merging lazy loading hotfix from rocm/release to develop

### PR DESCRIPTION
**Pull request by JeremyAdamHart**
Merging the release back into develop for the hotfix in [Tensile PR#1569](https://github.com/ROCmSoftwarePlatform/Tensile/pull/1569). It looks like this may have also picked up the commit from [PR#1543](https://github.com/ROCmSoftwarePlatform/Tensile/pull/1543), let me know if there is a reason this shouldn't be merged back into develop as well. As far as I can tell Tensile develop seems to already have those changes, just not the commit.

### CODE REVIEW

**Comment by benjaminulmer** [comment]
Shoot. I should've caught the formatting mistakes going into the release branch, but at the end of the day it doesn't have any functional impact so I guess we'll just have to live with it. Could you add a commit to this PR addressing the formatting issues so we don't propagate the failures into develop?

**Comment by benjaminulmer** [comment]
And yes, carrying in the merge commit is normal

**Comment by JeremyAdamHart** [comment]
@benjaminulmer Just pushed the fix for the formatting errors, should have caught that before too

**Review by benjaminulmer — APPROVED** [review]
Please make sure you do a regular merge (_not_ squash merge)

**Pull request merged**
