### PR TITLE
New JSD metric and metric selection functionality

### PR DESCRIPTION
**Pull request by afanfa**
This PR adds a new distance metric (even though is not technically a metric) and sketches a new functionality in Tensile to select a particular distance metric based on the value of the USE_METRIC environment variable.
The assignment a certain integer value to a metric is currently done statically. A better solution would be to rely on a method (sketched) in the class Distance to retrieve the right index. 
Suggestions on how to implement this new functionality in a clean way are more than welcome.

### CODE REVIEW

**Review by benjaminulmer — COMMENTED** [review]
Instead of adding an index to each distance metric, could we just have the USE_METRIC variable be a string that matches the `type()` method? This would both make the variable more intuitive to use and would remove the need for the `get_distance_id()` method you sketched.

**Comment by benjaminulmer** [comment]
Also I see this is targeting master. At some point the default branch on GitHub got switched to master instead of develop; could you retarget to develop please.

**Comment by afanfa** [comment]
> Instead of adding an index to each distance metric, could we just have the USE_METRIC variable be a string that matches the `type()` method? This would both make the variable more intuitive to use and would remove the need for the `get_distance_id()` method you sketched.

Sure, I like the idea. I default to numbers because it makes easier for me to test the various options with a loop in a bash script. Using strings instead of numbers for metrics makes more sense and reduces the risk of errors.

**Comment by zaliu** [comment]
@afanfa Please see @eidenyoshida's pinning clang-format to ROCm 4.3.1 [announcement](https://teams.microsoft.com/l/message/19:5818907f6c8b4637a19276b60b3cf5bf@thread.skype/1632348609913?tenantId=3dd8961f-e488-4e60-8e11-a82d994e183d&groupId=ac2278ba-8e20-4f39-b829-5ad102f224ef&parentMessageId=1632348609913&teamName=MLSE%20Libraries&channelName=Development%20Process&createdTime=1632348609913) for the appropriate version of clang-format to use.

**Review by benjaminulmer — APPROVED** [review]
It shouldn't be related to your changes, but I restarted the failed integration test just to be safe.

This doesn't change the default behaviour of Tensile at all and will be a useful feature for developing the two-tier solution selection approach. LGTM once CI clears.

**Comment by afanfa** [comment]
thanks @benjaminulmer . I have a question about the error message returned when the metric specified by TENSILE_METRIC is not found:

rocBLAS error: Could not load /home/alex/rocBLAS/build/release/rocblas-install/lib/../../Tensile/library/TensileLibrary.dat

rocBLAS error: Could not initialize Tensile library

It seems like the caller doesn't check for errors in the metric selection. Any suggestions on how to fix this?

**Review by zaliu — CHANGES_REQUESTED** [review]
Logistically, please confirm that this PR can build and pass rocblas-test fully on at least gfx908 and gfx90a.  Thanks.

**Comment by benjaminulmer** [comment]
> thanks @benjaminulmer . I have a question about the error message returned when the metric specified by TENSILE_METRIC is not found:
> 
> rocBLAS error: Could not load /home/alex/rocBLAS/build/release/rocblas-install/lib/../../Tensile/library/TensileLibrary.dat
> 
> rocBLAS error: Could not initialize Tensile library
> 
> It seems like the caller doesn't check for errors in the metric selection. Any suggestions on how to fix this?

I guess there's two sides to this. On the [rocBLAS side](https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/blob/433ef8dd1ce0539196c2de94dfe7ef41b6674f77/library/src/tensile_host.cpp#L668), we don't do any checks around loading the Tensile library besides success/failure. However, on the [Tensile side](https://github.com/ROCmSoftwarePlatform/Tensile/blob/75b9aefe5981d85d1df32ddcebf32dab52bfdabd/Tensile/Source/lib/source/Tensile.cpp#L54), we're not communicating any information about what caused the failure, so rocBLAS doesn't have any other option currently.

Step 1 would be to fix the Tensile side. I would need to look closer into the (de)serialization to see exactly how to get the error messages out, but I don't think it should be too difficult. We then would need to decide on how `LoadLibraryFile` should communicate these errors with the caller. Once the necessary changes are in place in Tensile, we can update rocBLAS to make use of them.

**Comment by benjaminulmer** [comment]
> Logistically, please confirm that this PR can build and pass rocblas-test fully on at least gfx908 and gfx90a. Thanks.

Hi Alex.

Is there a more "official" way to do this other than running manually? Either way, I can see to this task.

**Comment by zaliu** [comment]
> Is there a more "official" way to do this other than running manually?

On each of gfx908 and gfx90a, clone the develop branch of Tensile, then:
```
git remote add upstream https://github.com/ROCmSoftwarePlatform/Tensile.git
git fetch upstream pull/1448/head:pr-1448
git checkout pr-1448
```
Then build rocBLAS with the local Tensile repo.  Nothing "official" here, but pretty straightforward.  Thanks.

**Comment by afanfa** [comment]
I've successfully tested this PR on gfx90a. I can successfully compile and run rocblas-bench and the new functionality works as expected.

**Comment by benjaminulmer** [comment]
Sorry I got distracted by some things that came up. I just started the tests on 908 and 90a; will update when they're done. I don't expect any issues, however.

**Comment by benjaminulmer** [comment]
rocblas-test passed fully on 908 and 90a

**Review by zaliu — APPROVED** [review]

**Comment by zaliu** [comment]
Please squash-merge when you're ready.  Thanks.

**Pull request merged**
