### PR TITLE
Mainline update

### PR DESCRIPTION
**Pull request by babakpst**
This PR merges develop into mainline. Fast-forward merge was not possible due to a commit on Sep 15. 
It is related to [SWDEV-373943](https://ontrack-internal.amd.com/browse/SWDEV-373943).

### CODE REVIEW

**Comment by TorreZuk** [comment]
Okay just to make sure I follow what you are doing, will you be getting Lingamurty to update the manifest to commit 8be2a4d9e555eb5602b8ac9cff3dce48ad890b9d ?   @lawruble13 will your script manage this next update now that the mainline branch has extra manual commits not in staging?     The current commit for tensile in manifest file doesn't make sense to me,  dfb9ed277dcfca62b72a38e6dd27c00ca6f0b630 was it a mistake?

**Comment by babakpst** [comment]
- Yes, I will ask Ligamurty to update the manifest to commit 8be2a4d.
- We have yet to figure out the best approach here. We are open to any suggestions you have. 
- On the commit in the manifest, we discussed this today, and we wonder why the manifest is pointing to this commit. I am unsure if that commit in the mainline was necessary, and I did not want to delete the commit. So, I had to merge it for now. Hopefully, we will finalize the procedure as soon.

**Comment by TorreZuk** [comment]
Okay sounds good.  I would have first asked Lingamurty to update the manifest to the commit you wanted to see if Lauren's script would auto force the mainline branch.  Only if it failed do a PR or force push.  Can discuss tomorrow if you want but probably just need the manifest set.

**Comment by babakpst** [comment]
It would be great if I can have a 15-min meeting with you to discuss this procedure. I will setup a meeting in the afternoon. I optionally invite @AlexBrownAMD and @yoichiyoshida. Thanks.

**Pull request merged**
