### PR TITLE
Add predicate for BufferLoadOffsetLimitCheck when Beta!=0

### PR DESCRIPTION
**Pull request by exd94e**
rocBLAS verification is done

### CODE REVIEW

**Comment by zaliu** [comment]
@exd94e Please see @eidenyoshida's pinning clang-format to ROCm 4.3.1 [announcement](https://teams.microsoft.com/l/message/19:5818907f6c8b4637a19276b60b3cf5bf@thread.skype/1632348609913?tenantId=3dd8961f-e488-4e60-8e11-a82d994e183d&groupId=ac2278ba-8e20-4f39-b829-5ad102f224ef&parentMessageId=1632348609913&teamName=MLSE%20Libraries&channelName=Development%20Process&createdTime=1632348609913) for the appropriate version of clang-format to use.  Thanks.

**Comment by exd94e** [comment]
> @exd94e Please see @eidenyoshida's pinning clang-format to ROCm 4.3.1 [announcement](https://teams.microsoft.com/l/message/19:5818907f6c8b4637a19276b60b3cf5bf@thread.skype/1632348609913?tenantId=3dd8961f-e488-4e60-8e11-a82d994e183d&groupId=ac2278ba-8e20-4f39-b829-5ad102f224ef&parentMessageId=1632348609913&teamName=MLSE%20Libraries&channelName=Development%20Process&createdTime=1632348609913) for the appropriate version of clang-format to use. Thanks.

**Review by benjaminulmer — APPROVED** [review]
lgtm

**Comment by zaliu** [comment]
@exd94e please squash-merge when you're ready.  The gfx1030 test failure appears random, please ignore.  If you need help merging, let me know.  Thanks.

**Comment by exd94e** [comment]
@zaliu 
Should I merge by myself?
Currently, I am not authorized to merge this pull request.

**Pull request merged**
