### PR TITLE
Update some files with new clang-format

### PR DESCRIPTION
**Pull request by AlexBrownAMD**

### CODE REVIEW

**Review by cgmillette — APPROVED** [review]
LGTM

**Comment by cgmillette** [comment]
Does the CI have the updated clang formatting? It seems to be complaining about the changes

**Comment by leekillough** [comment]
> 
> 
> Does the CI have the updated clang formatting? It seems to be complaining about the changes

You can run `.githooks/pre-commit --reformat` to reformat the entire repo.

**Comment by zaliu** [comment]
> You can run `.githooks/pre-commit --reformat` to reformat the entire repo.

If you're running a version of ROCm build locally that has a different version of clang-format from what CI uses, problems can arise.

**Comment by AlexBrownAMD** [comment]
Yea, looks like clang-format has had a number of changes recently. Standard 3.8 build is different than newer bleeding-edge build, and both are also different from 3.7 many test on locally.

**Pull request closed without merging**
