### PR TITLE
fix GSU bug: PostGSU kernel refer to Nan data of C matrix even when b…

### PR DESCRIPTION
**Pull request by jichangjichang**
…eta is zero

### CODE REVIEW

**Review by aazz44ss — APPROVED** [review]
LGTM

**Review by imcarsonliao — APPROVED** [review]

**Comment by jichangjichang** [comment]
build rocblas with PR Tensile, rocblas-test results are all pass.
[----------] Global test environment tear-down
[==========] 1260834 tests from 510 test suites ran. (19298742 ms total)
[  PASSED  ] 1260834 tests.
rocBLAS version: 2.32.0.2843-1b7ee568 (new Tensile client)

rocblas: https://github.com/ROCmSoftwarePlatform/rocBLAS/tree/rocm-3.10.x
Tensile: https://github.com/ROCmSoftwarePlatform/Tensile/tree/rocm-3.10.x  + This commit

**Review by zaliu — APPROVED** [review]

**Comment by rosenrodt** [comment]
Are we going to add the test cases in Tensile as well as in rocBLAS?

**Comment by jichangjichang** [comment]
> Are we going to add the test cases in Tensile as well as in rocBLAS?
no plan for hotfix
For Tensile develop, we can simply apply init-data of C matrix as NaN for GSU precheck-in test.

**Comment by jichangjichang** [comment]
Failed CI tests are not caused by this PR.

**Pull request merged**
