### PR TITLE
Updating to Googletest 1.11.0

### PR DESCRIPTION
**Pull request by pavahora**

### CODE REVIEW

**Review by benjaminulmer — CHANGES_REQUESTED** [review]
The script you modified isn't used for CI/testing purposes. In order to update the version of googletest used for that, the commit of the googletest submodule needs to be updated. It looks like the commit for 1.11.0 is e2239ee6043f73722e7aa812a459f54a28552929.

```
git submodule update --init
cd HostLibraryTests/googletest
git fetch
git checkout e2239ee6043f73722e7aa812a459f54a28552929
cd ../..
git add HostLibraryTests/googletest
```

then commit and push.

Also, is there a reason this is targeted against master instead of develop?

**Review by benjaminulmer — APPROVED** [review]
lgtm pending CI; GFX1030 is flaky right now, but every other architecture is expected to fully pass

Please squash and merge if/when CI passes. Thanks

**Comment by eidenyoshida** [comment]
@zaliu @AlexBrownAMD @lawruble13 
Tensile::FATAL: Can't open "/tmp/.tensile-tox/py36/tmp/popen-gw3/test_nchw_stride_filter_Run_Co2/1_BenchmarkProblems/Cijkl_Anmijol_Bnmokl_S_00/Data/00_Final.csv" to get results

http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2Fextended%2FTensile/detail/PR-1437/1/pipeline/438#step-441-log-1202

This is worrying, has this issue been seen recently? Or is it due to the changes in the PR?

**Comment by benjaminulmer** [comment]
Yes gfx1030 has been sporadically failing for a while now

**Pull request merged**
