### PR TITLE
TransposeLds fixes

### PR DESCRIPTION
**Pull request by ramjana**
- transposeLDS fixes for bf16..
- re-worked equations for srcA/srcB register requirements

### CODE REVIEW

**Comment by rosenrodt** [comment]
I see that when generating HPA HGEMM with LocalReadVectorWidth=4, the `ds_read` instruction incorrectly chooses the `b128` variant when it really means `b64`. Should be an easy fix though

```
.protected Cijk_Alik_Bljk_HBH_MT32x256x16_MI32x32x4x2_SE_K1_LRVW4
...
/* local read prefetch a */
ds_read_b128 v[vgprValuA_X0_I0+0:vgprValuA_X0_I0+0+3], v[vgprLocalReadAddrA] offset:0 // L -> Reg lro=0 swapByteOffset=0 ti=32 vIdx=0 rIdx=0 oIdx=0 buffer=0 iui=0
```

**Comment by rosenrodt** [comment]
Also: validation fails when PrefetchLocalRead=0, InnerUnroll=2. 

```
0, 0/2, 6/7, Contraction_l_Alik_Bljk_Cijk_Dijk, "(3840,4096,1,4096)", Cijk_Alik_Bljk_HBH_MT32x256x32_MI32x32x4x2_SE_IU2_K1_LBSPP256_PLR0_TLDS1, FAILED, 4190.40, 30749, 33.00, 1289.00, 750.00, 1200.00, 0, 1, 2020-03-30 22:39:30.581343
```

**Comment by ramjana** [comment]
> I see that when generating HPA HGEMM with LocalReadVectorWidth=4, the `ds_read` instruction incorrectly chooses the `b128` variant when it really means `b64`. Should be an easy fix though
> 
> ```
> .protected Cijk_Alik_Bljk_HBH_MT32x256x16_MI32x32x4x2_SE_K1_LRVW4
> ...
> /* local read prefetch a */
> ds_read_b128 v[vgprValuA_X0_I0+0:vgprValuA_X0_I0+0+3], v[vgprLocalReadAddrA] offset:0 // L -> Reg lro=0 swapByteOffset=0 ti=32 vIdx=0 rIdx=0 oIdx=0 buffer=0 iui=0
> ```
> 
> EDIT: some LocalReadVectorWidth combo e.g., `LRVW=8` & `mi32x32x4x2` should be automatically rejected to prevent inevitable validation failure


LocalReadVectorWidth should be used to fetch more elements (>matrixInstK) along dimension. most preferably with innerUnroll>1.  parameter requires little more work before it can be used..

**Comment by rosenrodt** [comment]
Hopefully we can merge this PR fast after:
1.  PrefetchLocalRead=0, InnerUnroll=2 case taken care of 
2. To avoid future regression, add the above case to the test yaml 

> LocalReadVectorWidth should be used to fetch more elements (>matrixInstK) along dimension. most preferably with innerUnroll>1. parameter requires little more work before it can be used..

Looks like a fine idea.

**Comment by rosenrodt** [comment]
> LocalReadVectorWidth should be used to fetch more elements (>matrixInstK) along dimension. most preferably with innerUnroll>1. 

Looks like a fine idea.

**Pull request merged**
