### PR TITLE
Remove hcc support

### PR DESCRIPTION
**Pull request by AlexBrownAMD**
Since hcc has been deprecated for a while now, this change removes support in tensile. This change currently leaves options and global params like --cxx-compiler and CxxCompiler in place.

### CODE REVIEW

**Review by zaliu — APPROVED** [review]
The shortage of gfx908 CI executors is really getting to be a problem, @saadrahim @eidenyoshida .  The weekend planned shutdown didn't help.

**Comment by saadrahim** [comment]
CI is not running on this due to the branch conflict. Not sure if gfx908 shortages are impacting this.

**Comment by zaliu** [comment]
There wasn't any merge conflict when the timeouts took place earlier this morning and yesterday.  I just merged in a guest PR that caused this merge conflict within the past hour or so.

**Review by cgmillette — APPROVED** [review]
LGTM. 
Only thing I would ponder is whether to keep the tensile option for cxx-compiler in case we needed to need to differentiate with a future release again with another supported compiler. Otherwise, nice to clean a bunch of stuff up :)

**Comment by AlexBrownAMD** [comment]
> LGTM.
> Only thing I would ponder is whether to keep the tensile option for cxx-compiler in case we needed to need to differentiate with a future release again with another supported compiler. Otherwise, nice to clean a bunch of stuff up :)

Thanks for reviewing! Yea, I left the cxx-compiler option in for now, we can review if it should also be removed later.

**Pull request merged**
