### PR TITLE
add tensile_bfloat8 data type

### PR DESCRIPTION
**Pull request by settle**
If bfloat16 is truncated single-precision floating-point datatype, then bfloat8 is truncated half-precision floating-point datatype.  The addition of tensile_bfloat8 attempts to follow the example provided with tensile_bfloat16.

### CODE REVIEW

**Comment by settle** [comment]
Any way I can view the build report?  The details link is inaccessible to me.

**Comment by settle** [comment]
@amcamd Given that I see you added the bfloat16 support, is this something you'd be interested in and able to help?

**Comment by amcamd** [comment]
@settle Is it possible for you to provide a use case for bfloat8? If it is convenient, my email is in my GitHub profile. 

You should be able to run tests with

> cd Tensile
> PYTHONPATH=. py.test-3 --durations=0 -v Tensile/Tests/pre_checkin

Your code is failing with 
tensile_bfloat8.h:60:60: error: unknown type name 'TensileHalf'
[gfx900]     explicit __host__ __device__ constexpr tensile_bfloat8(TensileHalf f) : data(half_to_bfloat8(f)) {}

You should be able to fix this by replacing TensileHalf in  tensile_bfloat8.h  with   _Float16

**Comment by settle** [comment]
@amcamd I tried the following, but I must be missing something because everything fails and doesn't give me any errors like what you provided:

>sudo docker run -it --rm rocm/dev-ubuntu-18.04
>apt-get update
>apt-get install -y git vim python3-yaml python3-pytest
>cd /opt
>git clone https://github.com/ROCmSoftwarePlatform/Tensile.git
>cd Tensile
>PYTHONPATH=. py.test-3 --durations=0 -v Tensile/Tests/pre_checkin

I tried following the [Tensile Wiki](https://github.com/RadeonOpenCompute/Tensile/wiki), but it seems incomplete, outdated, or maybe I'm just not using the correct system config?  I can't quite tell from the wiki.

**Pull request closed without merging**
