### PR TITLE
initialize empty items

### PR DESCRIPTION
**Pull request by ce1adon**

### CODE REVIEW

**Comment by daniellowell** [comment]
Looks like there are quite a few failing tests. I am not familiar with your CI, is this normal, or are we shooting for all green check marks? @sdquiring can you assist us on getting this PR merged?

**Comment by sdquiring** [comment]
Our CI was recently enhanced to include some newer configurations which are broken in develop as well.  This is still ok to merge.

**Comment by daniellowell** [comment]
Thanks Scott!

**Comment by ce1adon** [comment]
Thank you Scott! Correspondingly we will update the mio-tensile dependencies. @pfultz2

**Pull request merged**
