### PR TITLE
Feature split vector

### PR DESCRIPTION
**Pull request by bensander**
Includes BufferLoad PR, just last commit "Add GlobalReadVectorWidth" is new.

### CODE REVIEW

**Comment by kknox** [comment]
Do you mean that bd36982 & 7195053 are duplicate commits?   If so, I will squash this to 1 commit

**Comment by bensander** [comment]
This includes commits which are also contained in #151.  So need to review & merge that first, then this one.

**Comment by bensander** [comment]
Rebased on updated.  This PR is for test only, setting the new GlobalReadVectorWidth=1 needs more performance testing.

**Comment by bensander** [comment]
New version : set default to match VW.  If this passes, let's merge.

**Comment by jgoldsAMD** [comment]
Can we get this merged? Would be helpful for the changes I am making to allow for mixed precision.

**Pull request merged**
