### PR TITLE
Check environment variables to override path to rocm

### PR DESCRIPTION
**Pull request by AlexBrownAMD**
default to /opt/rocm, but overridden by ROCM_ROOT, ROCM_PATH, TENSILE_ROCM_PATH

### CODE REVIEW

**Review by sdquiring — APPROVED** [review]
LGTM, I'd like to see CI pass on this.

**Review by zaliu — COMMENTED** [review]
We don't need to check for ${ROCM_ROOT}, given that rocBLAS only checks for ROCM_PATH.

**Comment by cgmillette** [comment]
Anyone else use ROCM_ROOT?

**Comment by zaliu** [comment]
For Stage-2 build, the DevOps build scripts do set ROCM_ROOT, but they don't pass ROCM_ROOT downstream, only ROCM_PATH:

```
ARG ROCM_PATH=/opt/rocm-$ROCM_VERSION
ENV ROCM_PATH=${ROCM_PATH}
ENV ROCM_ROOT=${ROCM_PATH}
```

**Review by cgmillette — APPROVED** [review]
LGTM

**Review by zaliu — APPROVED** [review]

**Comment by zaliu** [comment]
I removed the symlink /opt/rocm from 4083-STG1, set the environment variable ROCM_PATH=/opt/rocm-3.10.0-4083, and cherry-picked the commits in this PR to my local Tensile master, and a build of rocBLAS master branch with my local Tensile master worked just fine.

**Comment by zaliu** [comment]
Since precheckin passed and extended failures are not related to this PR.  I'm merging it to catch the Monday targetid train.  Thanks.

**Pull request merged**
