### PR TITLE
Removed unused CustomKernels and ReplacementKernels.

### PR DESCRIPTION
**Pull request by pkamd**
Solves [LWPTENSILE-432](https://ontrack-internal.amd.com/browse/LWPTENSILE-432)
Removed binary files in /Tensile/ReplacementKernels-cov3/ and /Tensile/CustomKernels/MDA2_Kernel1.s

### CODE REVIEW

**Comment by nakajee** [comment]
It looks like we need to remove Tensile unit test for ReplacementKernels.

**Review by AlexBrownAMD — APPROVED** [review]
Looks good to me!

**Comment by nakajee** [comment]
Please re-run precheckin CI test.
It failed with a known issue (not related to this change).
I would like to make sure all tests pass with this change.

**Review by nakajee — APPROVED** [review]
All tests passed

**Review by babakpst — APPROVED** [review]

**Pull request merged**
