### PR TITLE
Split LDS optimization

### PR DESCRIPTION
**Pull request by rosenrodt**
Furthering #1214's development, this patch boosts performance when `DepthULdsDivisor` > 1, meaning during accumulation loop you want to split the data intended for writing into LDS by a factor of `DepthULdsDivisor` 

- Schedule load instructions in the unroll loop earlier
- Improves performance in higher occupancy kernel via `s_setpro` in appropriate places
- Extends support for int8/fp32c/fp64
- Fix kernel generation when `DepthULdsDivisor` = 4

### CODE REVIEW

**Comment by rosenrodt** [comment]
rocblas-test on gfx908 passed

**Comment by zaliu** [comment]
@imcarsonliao please get this peer-reviewed.  Thanks.

**Review by AlexBrownAMD — APPROVED** [review]
LGTM

**Review by aazz44ss — APPROVED** [review]
LGTM

**Comment by rosenrodt** [comment]
CI errors seem to be associated with hw or runtime. Merging.

```
...
0,0/27,2/19,Contraction_mn_Amijkn_Bmlnk_Cijkl_Dijkl,"(5,3,32,16,120,8)",Cijkl_Amijkn_Bmlnk_S_MT64x128x4_SN_ASEM4_GSU1_K1_PBD0_PSD1,PASSED,862.834,17.0897,,0.00732422,0.5,64,0.234375,0.125,0.5,0.5,86400,30720,35,852,960,945,0,1,2021-06-25 06:21:20.010009
0,0/27,3/19,Contraction_mn_Amijkn_Bmlnk_Cijkl_Dijkl,"(5,3,32,16,120,8)",Cijkl_Amijkn_Bmlnk_S_MT64x128x4_SN_ASEM4_GSU1_K1_PBD1_PSD1,PASSED,863.13,17.0839,,0.00732422,0.125,64,0.9375,0.125,0.125,0.5,86400,30720,35,852,960,945,0,1,2021-06-25 06:21:20.014947
Exception occurred: Error 400(hipErrorInvalidHandle) /tmp/.tensile-tox/py36/lib/python3.6/site-packages/Tensile/Source/client/source/BenchmarkTimer.cpp:213: 
hipEventElapsedTime( &enqTime, startEvents->at(i).front(), stopEvents->at(i).back())
hipErrorInvalidHandle
```

**Pull request merged**
