### PR TITLE
Support N = 1 for TN and NN kernel

### PR DESCRIPTION
**Pull request by jichangjichang**
Original:
- min supported free size of a solution is limited by GRVW

Changes:
-min supported free size is limited by GLVW (actual global load vector width)
-min supported free size is limited only when memory of matrix is in free dim continuous.
-Separate the size checking for Free0 and Free1

Benefit:
-TN kernel have on limitation on M or N size
(can support M=1 or N=1 for any grvw )
-NN kernel only has limitation on M size 
(can support N=1 for any grvw )
-TT kernel only has limitation on N size 
(can support M=1 for any grvw )

### CODE REVIEW

**Comment by zaliu** [comment]
@imcarsonliao, can you get somebody on your team to do a peer review first?  Thanks.

**Review by imcarsonliao — APPROVED** [review]
LGTM. Currently leave NT to other approaches.

**Comment by jichangjichang** [comment]
@zaliu @AlexBrownAMD @sdquiring could you take time to review this PR? we would like to enable this for rocm3.9

**Comment by jichangjichang** [comment]
> LGTM (check the clang-format messages)

All changed files of this PR pass the clang-format checking.
 (clang-format checking failed on other files that is not relevant to this PR. )

**Pull request merged**
