### PR TITLE
Fix merge error affecting i8 with wmma

### PR DESCRIPTION
**Pull request by AlexBrownAMD**
Error affects gfx1100 in builds after gfx940 merge. Bug caused by missing modifier to wmma instructions.

### CODE REVIEW

**Review by TorreZuk — COMMENTED** [review]
Very good to see!  Hopefully gets a quick tensile review expect we want to cherry pick as hotfix 5.7 , correct?

**Comment by AlexBrownAMD** [comment]
> Very good to see! Hopefully gets a quick tensile review expect we want to cherry pick as hotfix 5.7 , correct?

Yes, the affected changeset is also on the 5.7 staging branch

**Review by yoichiyoshida — COMMENTED** [review]
LGTM

**Review by yoichiyoshida — APPROVED** [review]

**Comment by AlexBrownAMD** [comment]
Ran all rocblas gemm i8 tests on gfx1100 with this patch and all are now passing.

**Comment by TorreZuk** [comment]
> Ran all rocblas gemm i8 tests on gfx1100 with this patch and all are now passing.

Thanks for saving me the testing!

**Pull request merged**
