### PR TITLE
NonTemporalD

### PR DESCRIPTION
**Pull request by aazz44ss**
based on definition of D = alpha * A x B + beta * C

## origin
NonTemporalA for loadA
NonTemporalB for loadB
no NonTemporal parameter for loadC
NonTemporalC for storeD

## new
NonTemporalA for loadA
NonTemporalB for loadB
NonTemproalC for loadC
NonTemporalD for storeD

### CODE REVIEW

**Review by imcarsonliao — APPROVED** [review]
LGTM.   (Would the naming be a little bit confusing when there is no C or so-called C equals to D? )

**Comment by aazz44ss** [comment]
> LGTM. (Would the naming be a little bit confusing when there is no C or so-called C equals to D? )

there is no kernel code difference if CequalsD.
kernel code still load from C and store to D, and C and D address are assigned to the same buffer in host code.

**Comment by zaliu** [comment]
@aazz44ss if this PR is for the current ROCm release, we need to re-target to the master branch.  @bragadeesh should we target the current ROCm release?  Please advise.  Thanks.

**Comment by aazz44ss** [comment]
@zaliu 
This PR can further increase HPL performance, but need to retuned with parameters introduced by this PR.

**Review by jichangjichang — COMMENTED** [review]
LGTM

**Review by yoichiyoshida — APPROVED** [review]

**Pull request merged**
